### ISSUE TITLE
Uncaught TypeError: _styled.button is not a function

### ISSUE THREAD

**Issue by GAZ082** [syradar/yxans-klagan#242]
Right after starting with `npm run start` I get in the webapp:

![image](https://user-images.githubusercontent.com/100194/209817214-8e391b8b-c0d5-4649-b1d2-e34424386988.png)

**Comment by syradar** [comment]
@GAZ082 I have updated all the dependencies and started to improve the app. You should be able to get it working now

**Comment by GAZ082** [comment]
Mmm!

After rpm run dev:

```0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.24.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
7 info using npm@5.8.0
8 info using node@v10.24.0
9 verbose run-script [ 'predev', 'dev', 'postdev' ]
10 info lifecycle yxans-klagan@1.2.0~predev: yxans-klagan@1.2.0
11 info lifecycle yxans-klagan@1.2.0~dev: yxans-klagan@1.2.0
12 verbose lifecycle yxans-klagan@1.2.0~dev: unsafe-perm in lifecycle true
13 verbose lifecycle yxans-klagan@1.2.0~dev: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/gabriel/repos/yxans-klagan/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
14 verbose lifecycle yxans-klagan@1.2.0~dev: CWD: /home/gabriel/repos/yxans-klagan
15 silly lifecycle yxans-klagan@1.2.0~dev: Args: [ '-c', 'vite' ]
16 silly lifecycle yxans-klagan@1.2.0~dev: Returned: code: 1  signal: null
17 info lifecycle yxans-klagan@1.2.0~dev: Failed to exec dev script
18 verbose stack Error: yxans-klagan@1.2.0 dev: `vite`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
18 verbose stack     at EventEmitter.emit (events.js:198:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:198:13)
18 verbose stack     at maybeClose (internal/child_process.js:982:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid yxans-klagan@1.2.0
20 verbose cwd /home/gabriel/repos/yxans-klagan
21 verbose Linux 5.10.102.1-microsoft-standard-WSL2
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
23 verbose node v10.24.0
24 verbose npm  v5.8.0
25 error code ELIFECYCLE
26 error errno 1
27 error yxans-klagan@1.2.0 dev: `vite`
27 error Exit status 1
28 error Failed at the yxans-klagan@1.2.0 dev script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]```

**Comment by syradar** [comment]
Yeah you will need to update node to at least version 16

**Comment by syradar** [comment]
You can use [nvm](https://github.com/nvm-sh/nvm) to manage your installed node versions

**Comment by syradar** [comment]
Closing due to inactivity
